app/models/model.py
from flask_mysqldb import MySQL
from wtforms import Form, validators , StringField, IntegerField

from app import mysql

class BookForm(Form):
   id = IntegerField("Id" , [validators.NumberRange(min=1)])
   title = StringField("Title" , [validators.Length(min=3 , max=255)])
   numPages = IntegerField("NumPages" , [validators.NumberRange(min=1)])
   author = StringField("Author" , [validators.Length(min=3 , max=1000)])  


def select_all_books():
    cursor = mysql.connection.cursor()
    cursor.execute(''' select * from books''')
    books = cursor.fetchall()
    cursor.close()
    mysql.connection.commit()
    return books

def select_book_using_id(id):
    cursor = mysql.connection.cursor()
    cursor.execute("SELECT * FROM books WHERE id=%s" , [id])
    book = cursor.fetchone()
    cursor.close()
    return book

def insert_book(title , numPages , Author):
    cursor = mysql.connection.cursor()
    cursor.execute("INSERT INTO books (title, NumPages, Author) values (%s,%s,%s);", (title,numPages,Author))
    cursor.close()
    mysql.connection.commit()


def delete_book(id):
    cursor = mysql.connection.cursor()
    cursor.execute("DELETE FROM books WHERE id=%s" , (id))
    cursor.close()
    mysql.connection.commit()


def update_book(title, numPages, Author, id):
    cursor = mysql.connection.cursor()
    cursor.execute("UPDATE books SET title=%s,numPages=%s,Author=%s WHERE id=%s" , [title,numPages,Author,id])
    book = cursor.fetchone()
    bookform = BookForm()
    cursor.close()
    mysql.connection.commit()
    return [book , bookform]


#---------------------------------------------------------------------------------------------


class MemberForm(Form):
   id = IntegerField("Id", [validators.NumberRange(min=1)])
   name = StringField("Name", [validators.Length(min=3)])
   lastname = StringField("LastName", [validators.Length(min=3)])
   username = StringField("UserName", [validators.Length(min=3)])
   password = StringField("Password", [validators.Length(min=8)])
   phonenumber = IntegerField("PhoneNumber", [validators.Length(min=8)])
   address = StringField("Address", [validators.Length(min=5 , max=1000)])

def select_all_members():
    cursor = mysql.connection.cursor()
    cursor.execute(''' select * from users''')
    members = cursor.fetchall()
    cursor.close()
    mysql.connection.commit()
    return members

def insert_member(name, lastname, username, password, phonenumber, address):
    cursor = mysql.connection.cursor()
    cursor.execute("INSERT INTO users (name, lastname, username, password, phonenumber, address) values (%s,%s,%s,%s,%s,%s);", [name, lastname, username, password, phonenumber, address])
    cursor.close()
    mysql.connection.commit()

def delete_member(id):
    cursor = mysql.connection.cursor()
    cursor.execute("DELETE FROM users WHERE id=%s" , [id])
    cursor.close()
    mysql.connection.commit()

def update_member(name,lastname,username,password,phonenumber,address,id):
    cursor = mysql.connection.cursor()
    cursor.execute("UPDATE users SET name=%s,lastname=%s,username=%s,password=%s,phonenumber=%s,address=%s WHERE id=%s" , [name,lastname,username,password,phonenumber,address,id])
    cursor.close()
    mysql.connection.commit()

def select_member_using_id(id):
    cursor = mysql.connection.cursor()
    cursor.execute("SELECT * FROM users WHERE id=%s" , [id])
    member = cursor.fetchone()
    memberform = MemberForm()
    cursor.close()
    return member

app/app.py
from flask import Flask , render_template , request , redirect , url_for
from flask_mysqldb import MySQL
from wtforms import Form, validators, StringField, FloatField, IntegerField, DateField, SelectField

app = Flask(__name__)

app.config['MYSQL_HOST'] = 'mysql'
app.config['MYSQL_USER'] = 'mahdi'
app.config['MYSQL_PASSWORD'] = '1234'
app.config['MYSQL_DB'] = 'LibraryApp'
app.config['MYSQL_PORT'] = 3306


mysql = MySQL()

@app.route('/')
def landing():
   return render_template("index.html")


if __name__ == '__main__':
   from routes.book import book_app
   from routes.member import user_app

   mysql.init_app(app)
   app.register_blueprint(book_app)
   app.register_blueprint(user_app)
   app.run(debug=True, host='0.0.0.0' , port=4000)

app/routes/book.py
from flask import Blueprint , render_template , request , redirect , url_for
from models.model import *

book_app = Blueprint('book', __name__, template_folder='templates')

@book_app.route('/books')
def list_books_route():
      books = select_all_books()
      return render_template("books.html" , books=books)

@book_app.route('/add_book' , methods={"GET" , "POST"})
def add_book_route():
    if request.method == "POST":
      form = BookForm(request.form)
      try: 
        insert_book(form.title.data,form.numPages.data,form.author.data)
        return redirect(url_for("book.list_books_route"))
      except Exception as e:
         return render_template("add_book.html" , form=form , error="Error : " + str(e)) , 400
    elif request.method == "GET":
      form = BookForm()
      return render_template("add_book.html" , form=form)
    

@book_app.route('/delete_book/' , methods={"POST"})
def delete_book_route():
    id = request.args.get('id')
    delete_book(id)
    return redirect(url_for("list_books_route"))



@book_app.route('/edit_book/<id>' , methods={"GET" , "POST"})
def edit_book_route(id):
    cursor = mysql.connection.cursor()
    [bookform , book] = select_book_using_id(id)
    print(book)
    if request.method == "POST":
      form = BookForm(request.form)
      try: 
        update_book(form.title.data,form.numPages.data,form.author.data,id)
        return redirect(url_for("list_books_route"))
      except Exception as e:
         return render_template("edit_book.html" , form=form , error="Error : " + str(e)) , 400
    elif request.method == "GET":
      return render_template("edit_book.html" , form=bookform , book=book)

app/routes/member.py
from flask import Blueprint, Flask , render_template , request , redirect , url_for
from models.model import *

user_app = Blueprint('user', __name__, template_folder='templates')

@user_app.route('/members')
def list_members_route():
      members = select_all_members()
      return render_template("members.html" , members=members)


@user_app.route('/add_member' , methods={"GET" , "POST"})
def add_member_route():
    if request.method == "POST":
      form = MemberForm(request.form)
      try:
        insert_member(form.name.data,form.lastname.data,form.username.data,form.password.data,form.phonenumber.data,form.address.data)
        return redirect(url_for("user.list_members_route"))
      except Exception as e: 
         return render_template("add_member.html" , form=form , error="Error : "+str(e)) , 400
    elif request.method == "GET":
      form = MemberForm()
      return render_template("add_member.html" , form=form)

# @user_app.route('/delete_member' , defaults={'id':None}, methods={"POST"})
@user_app.route('/delete_member' , methods={"POST"})
def delete_member_route():
    id = request.args.get('id')
    delete_member(id)
    return redirect(url_for("user.list_members_route"))


@user_app.route('/edit_member/<id>' , methods={"GET" , "POST"})
def edit_member_route(id):
    cursor = mysql.connection.cursor()
    member = select_member_using_id(id)
    print(member)
    if request.method == "POST":
      form = MemberForm(request.form)
      try:
        update_member(form.name.data,form.lastname.data,form.username.data,form.password.data,form.phonenumber.data,form.address.data,id)
        return redirect(url_for("user.list_members_route"))
      except Exception as e:
        return render_template("edit_member.html" , form=form , member=member , error ="Error : "+str(e)) , 400
    elif request.method == "GET":
      memberform = MemberForm()
      return render_template("edit_member.html" , form=memberform , member=member)

app/templates/add_book.html
{% extends 'layout.html' %}
{% block body %}
<br>
<h1>Add New Book</h1>
{% from "includes/_formhelpers.html" import render_field %}
<form method="POST" action="">
    <div class="form-group">
        {{render_field(form.title, class_="form-control")}}
    </div><br>
    <div class="form-group">
        {{render_field(form.numPages, class_="form-control")}}
    </div><br>
    <div class="form-group">
        {{render_field(form.author, class_="form-control")}}
    </div><br>
    <br>
    <p><button type="submit" class="btn btn-primary" value="Submit">Submit</button></p>
</form>
{% endblock %}

app/templates/add_member.html
{% extends 'layout.html' %}
{% block body %}
<br>
<h1>Add New Member</h1>
{% from "includes/_formhelpers.html" import render_field %}
<form method="POST" action="">
    <div class="form-group">
        {{render_field(form.name, class_="form-control")}}
    </div><br>
    <div class="form-group">
        {{render_field(form.lastname, class_="form-control")}}
    </div>
    <div class="form-group">
        {{render_field(form.username, class_="form-control")}}
    </div>
    <div class="form-group">
        {{render_field(form.password, class_="form-control")}}
    </div>
    <div class="form-group">
        {{render_field(form.phonenumber, class_="form-control")}}
    </div>
    <div class="form-group">
        {{render_field(form.address, class_="form-control")}}
    </div>
    <br>
    <p><button type="submit" class="btn btn-primary" value="Submit">Submit</button></p>
</form>
{% endblock %}

app/templates/books.html
{% extends 'layout.html' %}
{% block body %}
<br>
<h1>Books</h1>
<a class="btn btn-success" href="/add_book">Add New Book</a>
<!-- <a class="btn btn-secondary" href="/import_books">Import From API</a> -->
<hr>
{% if books %}
<table class="table table-hover table-striped">
    <thead>
        <tr>
            <th>Book ID</th>
            <th>Title</th>
            <th>Num Of Pages</th>
            <th>Author(s)</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for book in books %}
        <tr style="cursor:pointer;">
            <!-- <td><a href="/book/{{book[0]}}" class="btn btn-dark pull-right">{{book[0]}}</a></td> -->
            <td>{{book[0]}}</td>
            <td>{{book[1]}}</td>
            <td>{{book[2]}}</td>
            <td>{{book[3]}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endif %}
{% endblock %}

app/templates/edit_member.html
{% extends 'layout.html' %}
{% block body %}
<br>
<h1>Edit Member</h1>
{% from "includes/_formhelpers.html" import render_field %}
<form method="POST" action="">
    <div class="form-group">
        {{render_field(form.name, class_="form-control", value=member[1])}}
    </div><br>
    <div class="form-group">
        {{render_field(form.lastname, class_="form-control", value=member[2])}}
    </div><br>
    <div class="form-group">
        {{render_field(form.username, class_="form-control", value=member[3])}}
    </div><br>
    <div class="form-group">
        {{render_field(form.password, class_="form-control", value=member[4])}}
    </div><br>
    <div class="form-group">
        {{render_field(form.phonenumber, class_="form-control", value=member[5])}}
    </div><br>
    <div class="form-group">
        {{render_field(form.address, class_="form-control", value=member[6])}}
    </div>
    <br><br>
    <p><button type="submit" class="btn btn-primary" value="Submit">Submit</button></p>
</form>
{% endblock %}

app/templates/includes/_formhelpers.html
<!--https://flask.palletsprojects.com/en/2.0.x/patterns/wtforms/-->

{% macro render_field(field) %}
{{ field.label }}
{{ field(**kwargs)|safe }}
{% if field.errors %}
{% for error in field.errors %}
<div class="help-text-inline alert alert-warning" style="margin-top:10px; padding: 8px;">{{ error }}</div>
{% endfor %}
{% endif %}
{% endmacro %}

app/templates/includes/_messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
<br>
<div class="alert alert-{{ category }}">{{ message }}</div>
{% endfor %}
{% endif %}
{% endwith %}

{% if error %}
<br>
<div class="alert alert-danger">{{error}}</div>
{% endif %}

{% if warning %}
<br>
<div class="alert alert-warning">{{warning}}</div>
{% endif %}

{% if msg %}
<br>
<div class="alert alert-success">{{msg}}</div>
{% endif %}

app/templates/includes/_navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="/"><b>LibMS</b></a>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <!-- <li class="nav-item">
                    <a class="nav-link" href="/reports">Reports</a>
                </li> -->
                <li class="nav-item">
                    <a class="nav-link" href="/books">Books</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/members">Members</a>
                </li>
                <!-- <li class="nav-item">
                    <a class="nav-link" href="/transactions">Transactions</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/search_book">Search</a>
                </li> -->
            </ul>
        </div>
    </div>
</nav>

app/templates/index.html
{% extends 'layout.html' %}
{% block body %}
<div class="px-4 py-5 my-5 text-center">
    <h1 class="display-5 fw-bold">Library Management System</h1>
    <div class="col-lg-6 mx-auto">
        <p class="lead mb-4">A Library Management Web Application built in fulfilment of the <a
                href="https://frappe.io/dev-hiring-test" style="text-decoration: none; color: unset;">Developer Hiring
                Test for Frappe. Allows a librarian to track books and their quantity, members, and transactions.</a>
        </p>
        <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
            <!-- <a href="/reports" class="btn btn-primary btn-lg px-4">Reports</a> -->
            <a href="/books" class="btn btn-outline-secondary btn-lg px-4">Books</a>
            <a href="/members" class="btn btn-outline-secondary btn-lg px-4">Members</a>
            <!-- <a href="/transactions" class="btn btn-outline-secondary btn-lg px-4">Transactions</a> -->

        </div>
    </div>
</div>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Library Management Flask</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
</head>

<body>
    {% include 'includes/_navbar.html' %}
    <div class='container'>
        {% include 'includes/_messages.html' %}
        {% block body %}{% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>
</body>

</html>

app/templates/members.html
{% extends 'layout.html' %}
{% block body %}
<br>
<h1>Members</h1>
<a class="btn btn-success" href="/add_member">Add New Member</a>
<hr>
{% if members%}
<table class="table table-striped">
    <thead>
        <tr>
            <th>Member ID</th>
            <th>Name</th>
            <th>LastName</th>
            <th>UserName</th>
            <th>Phone Number</th>
            <th>Address</th>
        </tr>
    </thead>
    <tbody>
        {% for member in members %}
        <tr>
            <td>{{member[0]}}</td>
            <td>{{member[1]}}</td>
            <td>{{member[2]}}</td>
            <td>{{member[3]}}</td>
            <td>{{member[5]}}</td>
            <td>{{member[6]}}</td>
            <td><a href="edit_member/{{member[0]}}" class="btn btn-primary pull-right">Edit</a></td>
            <td>
                <form action="{{url_for('user.delete_member_route', id=member[0])}}" method="POST"
                    onsubmit="return confirm('Are you sure you want to delete this member?');">
                    <input type="hidden" name="method" value="Delete">
                    <input type="submit" value="Delete" class="btn btn-danger">
                </form>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endif %}
{% endblock %}